export enum ActionTypes {
    GET_TOP_NAVIGATION = "GET_TOP_NAVIGATION",
    GET_SIDE_NAVIGATION = "GET_SIDE_NAVIGATION",
    GET_SITES = "GET_SITES",
    SET_TOP_NAVIGATION = "SET_TOP_NAVIGATION",
    SET_SIDE_NAVIGATION = "SET_SIDE_NAVIGATION",
    SET_SITE = "SET_SITE",
  }