export enum MutationTypes {
     SET_CONTENT = "SET_CONTENT",
     SET_GRIDS = "SET_GRIDS",
     SET_FOLDERS = "SET_FOLDERS",
     SET_BUTTONS = "SET_BUTTONS",
     SET_PAGE = "SET_PAGE",
     SET_FORMS = "SET_FORMS",
     SET_RESOURCES = "SET_RESOURCES",
     SET_POST_CONTENT = "SET_POST_CONTENT",
     INCREMENT_SET_GET_CONTENT = "INCREMENT_SET_GET_CONTENT",
     DECREMENT_SET_GET_CONTENT = "DECREMENT_SET_GET_CONTENT",
  }