export enum ActionTypes {
    AUTHENTICATE = "AUTHENTICATE",
    UNAUTHENTICATE = "UNAUTHENTICATE",
    RESET_PASSWORD = "RESET_PASSWORD",
    SET_PROFILE = "SET_PROFILE",
    TOGGLE_LOGIN = "TOGGLE_LOGIN",
  }