export enum MediakiwiFormVueType {
  /* eslint no-undefined: 0*/
  undefined = 0,
  formButton = 1,
  formChoiceDropdown = 2,
  formPlus = 3,
  formRichText = 4,
  formText = 5,
  formTextline = 6,
  formTag = 7,
  formChoiceCheckbox = 8,
  formTextArea = 10,
  formChoiceRadio = 11,
  formDateTime = 12,
  formDate = 13,
  formSection = 14,
  formNameValueCollection = 15,
  formNameValue = 16,
  formTime = 17,
  formValueCollection = 18,
  formValue = 19,
  formLink = 20,
  formSublistSelect = 21,
}
