export enum MediakiwiFormVueType {
  wimButton = 1,
  wimChoiceDropdown = 2,
  wimPlus = 3,
  wimRichText = 4,
  wimText = 5,
  wimTextline = 6,
  wimTag = 7,
  wimChoiceCheckbox = 8,
  wimTagVue = 9,
  wimTextArea = 10,
  wimChoiceRadio = 11,
  wimDateTime = 12,
  wimDate = 13,
  wimSection = 14,
}
