export enum MutationTypes {
    SET_DRAWER_OPEN = "SET_DRAWER_OPEN",
    SET_DIALOG_OPEN = "SET_DIALOG_OPEN",
    SET_DIALOG_SETTINGS = "SET_DIALOG_SETTINGS",
    SET_OPEN_IN_FRAME = "SET_OPEN_IN_FRAME",
    SET_NOTIFICATION = "SET_NOTIFICATION",
    SET_LOADING = "SET_LOADING",
    TOGGLE_NOTIFICATION = "TOGGLE_NOTIFICATION",
  }